export const textBlack = "#121212";
export const textWhite = "#FFFFFF";
export const homeIntroText = ["This is a long line of text to test the limits of this animation.", "two", "3", "4.5", "true"];
export const p1ImgLoc = "https://frontendmasters.com/static-assets/learn/og-learning-path-react.jpg";
export const p1ImgAlt = "some react image here";
export const p1Title = "React application test";
export const p1Summary = "Made a React application for fun. This is another line to check for spacing";
export const p1Tags = [ {name:"React"},{name:"Web Design"},{name:"CSS"},{name:"UI/UX Design"},{name:"HTML5"}];
export const p2Tags = [{ name: "Not React" }, { name: "!@Web% /Design 1" }, { name: "UI/UX Design"},{name:"test1"},{name:"test# 1"}, {name:"test 2"}];
